language: python
python:
  - "3.7"
cache: pip
install: pip install . -r dev-requirements.txt
script:
  - pylint *.py **/*.py
  - pytest --doctest-modules
notifications:
  email:
    on_success: never
